  stages:
    - check
  
  check:
    stage: check
    script:
      - apt-get update
      - apt-get install -y spell
      - find . -name "*.txt" | xargs spell -no > spell.result
      - cat spell.result
      - if [[ "$(wc -l spell.result)" -gt "0" ]]; then exit 1; fi

